language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

script:
  - go test -v -race ./...

notifications:
  email:
    recipients:
      - info@miladrahimi.com
    on_success: change
    on_failure: always
